# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\nGreetReply\x12\x18\n\x10greeting_message\x18\x01 \x01(\t2<\n\x07Greeter\x12\x31\n\x05Greet\x12\x13.greet.GreetRequest\x1a\x11.greet.GreetReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GREETREQUEST']._serialized_start=22
  _globals['_GREETREQUEST']._serialized_end=50
  _globals['_GREETREPLY']._serialized_start=52
  _globals['_GREETREPLY']._serialized_end=90
  _globals['_GREETER']._serialized_start=92
  _globals['_GREETER']._serialized_end=152
# @@protoc_insertion_point(module_scope)
